upcn-utiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AfiliadoController;
use App\Http\Controllers\AsignacionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KitController;
//comentario
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function () {
    //Inicio
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');

    //Recursos ABMC
    Route::resources([
        'afiliados' => AfiliadoController::class,
        'asignaciones' => AsignacionController::class,
        'kits' => KitController::class
    ]);
    Route::get('/cargarStock',[KitController::class,'cargarStock'])->name('cargarStock');
    Route::post('/updateStock',[KitController::class,'updateStock'])->name('updateStock');
});

//Graficos
Route::get('/stock', [KitController::class, 'stock'])->name('stock');
Route::get('/stockGrafico', [KitController::class, 'stockGrafico'])->name('stockGrafico');
Route::get('/kitsEntregados', [KitController::class, 'kitsEntregados'])->name('kitsEntregados');
Route::get('/graficoKitsEntregados', [KitController::class, 'graficoKitsEntregados'])->name('graficoKitsEntregados');

//Datatables
Route::get('/datatable/asignaciones', [AsignacionController::class, 'asignaciones'])->name('datatable.asignaciones');

require __DIR__.'/auth.php';

upcn-utiles/app/Models/Afiliado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Afiliado extends Model
{
    // protected $table = 'afiliado';
    protected $primaryKey = 'idAfiliado';
    protected $fillable = [
        'nombre',
        'apellido',
        'dni',
        'email',
        'telefono',
        'localidad',
        'cantidadHijos',
        'tipoEmpleado'
    ];
    //relacion 1 a muchos con la tabla Asignacion
    public function asignaciones(){
        return $this->hasMany(Asignacion::class, 'fkIdAfiliado', 'idAfiliado');
    }
}

upcn-utiles/app/Http/Controllers/AfiliadoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Afiliado;
use Illuminate\Support\Facades\Validator;
use Exception;
use Illuminate\Database\Events\TransactionBeginning;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AfiliadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        try{
            $afiliados = Afiliado::all();
        }catch(Exception $e){
            abort(404);
        }

        return view('afiliados.index',['afiliados' => $afiliados]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('afiliados.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $afiliado = new Afiliado();
        //validacion de los datos que llegan por request
        $this->validarRequest($request);
        $telefono = $request->prefijo . $request->telefono;

        $afiliado->nombre =$request->nombre;
        $afiliado->apellido = $request->apellido;
        $afiliado->dni = $request->dni;
        $afiliado->email = isset($request->email) ? $request->email : '(falta email)';
        $afiliado->telefono = ($telefono != '') ? $telefono : '(falta telefono)';
        $afiliado->localidad = $request->localidad;
        $afiliado->cantidadHijos = $request->cantHijos;
        $afiliado->tipoEmpleado = $request->tipo;


        try{
            $existe = $this->existeAfiliado($afiliado->dni);
            if($existe){
                $data = array(
                    'status' => 'error',
                    'code' => '400',
                    'message' => 'Afiliado duplicado'
                );
            }else{
                //Beggintransaction
                $afiliado->save();
                $data = array(
                    'status' => 'success',
                    'code' => '200',
                    'message' => 'Afiliado creado'
                );
            }
            //commit
        }catch(Exception $e){
            //rollback
            $data = array(
                'status' => 'error',
                'code' => '400',
                'message' => 'El Afiliado no pudo ser creado'
            );
        }
        //despues redireccionar al listado de afiliados
        return redirect(route('afiliados.index'));
        //este return lo puse solo para ver donde estaba entrando
        // return response()->json($data,200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Afiliado  $afiliado
     * @return \Illuminate\Http\Response
     */
    public function show(Afiliado $afiliado)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Afiliado  $afiliado
     * @return \Illuminate\Http\Response
     */
    public function edit($idAfiliado){
        try{
            $afiliado = Afiliado::find($idAfiliado);
        }catch(Exception $e){
            $data = array(
                'status' => 'error',
                'code' => '400',
                'message' => 'El Afiliado no pudo ser recuperado'
            );
        }

        return view('afiliados.edit',['afiliado' => $afiliado]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Afiliado  $afiliado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
        $afiliado = Afiliado::find($id);
        //validar request
        $this->validarRequest($request);
        $telefono = $request->prefijo . $request->telefono;

        $afiliado->nombre =$request->nombre;
        $afiliado->apellido = $request->apellido;
        $afiliado->dni = $request->dni;
        $afiliado->email = isset($request->email) ? $request->email : '(falta email)';
        $afiliado->telefono = ($telefono != '') ? $telefono : '(falta telefono)';
        $afiliado->localidad = $request->localidad;
        $afiliado->cantidadHijos = $request->cantHijos;
        $afiliado->tipoEmpleado = $request->tipo;
        $afiliado->save();

        return redirect(route('afiliados.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Afiliado  $afiliado
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
        
        try{
            $afiliado = Afiliado::find($id);

            if($afiliado){
                $afiliado->delete();
                $data = array(
                    'status' => 'success',
                    'afiliado' => $afiliado
                );
            }else{
                $data = array(
                    'status' => 'error',
                    'message' => 'No se pudo encontrar el afiliado'
                );
            }
        }catch(Exception $e){
            $data = array(
                'status' => 'error',
                'message' => 'Error'
            );
            abort(404);
        }
        
        return redirect(route('afiliados.index'));
        // return response($data);
    }

    public function existeAfiliado($dni){
        $res = DB::table('afiliados')   ->where('dni', $dni)
                                        ->first();
        return $res;
    }

    //validacion de los datos que llegan por request
    public function validarRequest($request) : void{
        $validator = Validator::make($request->all(), [
            'nombre' => 'required',
            'apellido' => 'required',
            'dni' => 'required',
            'localidad' => 'required',
            'cantHijos' => 'required',
            'tipo' => 'required',
        ]);
        if ($validator->fails()) {
            //se manda automaticamente la variable $errors al blade
            //habria que cambiar a otro blade, solo estaba probando
            // return redirect(route('404'))
            //             ->withErrors($validator)
            //             ->withInput();
            abort(404);
        }
    }
}

upcn-utiles/resources/views/afiliados/create.blade.php
@extends('layouts.layout')
@section('title','Crear Afiliado')

@section('content')
    <div class="card w-75 border-secondary">
        <div class="card-header" >
            <h3>Crear nuevo afiliado</h3>
        </div>

        <div class="card-body">
            <form action={{route('afiliados.store')}} method="POST">
                @csrf

                <div class="form-group row">
                    <label for="nombre">Nombre completo del afiliado (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="nombre" name="nombre" placeholder="Nombre" required>
                    </div>

                    <div class="col">
                        <input class="form-control" type="text" id="apellido" name="apellido" placeholder="Apellido" required>    
                    </div>
                </div>

                <div class="form-group row">
                    <label for="dni">Dni (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="dni" name="dni" placeholder="Dni" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email">Email</label>
                    <div class="col">
                        <input class="form-control" type="email" id="email" name="email" placeholder="ejemplo@ejemplo.com">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="prefijo">Telefono</label>
                    <div class="col">
                        <input class="form-control" type="text" id="prefijo" name="prefijo" placeholder="Prefijo sin el 0">
                    </div>

                    <div class="col">
                        <input class="form-control" type="text" id="telefono" name="telefono" placeholder="Numero de telefono sin el 15">    
                    </div>
                </div>

                <div class="form-group row">
                    <label for="localidad">Localidad (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="localidad" name="localidad" placeholder="Ciudad" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="cantHijos">Cantidad de hijos (*)</label>
                    <div class="col">
                        <select class="form-select" name="cantHijos" id="cantHijos" required>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="3">4</option>
                            <option value="3">5</option>
                          </select>
                        
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tipo">Tipo de Empleado (*)</label>
                    <div class="col">
                        <select class="form-select" name="tipo" id="tipo" required>
                            <option value="publico">Empleado Público</option>
                            <option value="municipal">Empleado Municipal</option>
                        </select>
                    </div>
                </div>

                <button class="btn btn-success" id="crear" type="submit">Crear</button>

            </form>
        </div>
    </div>
@endsection

upcn-utiles/resources/views/afiliados/edit.blade.php
@extends('layouts.layout')
@section('title','Editar Afiliado')

@section('content')
    <div class="card w-75 border-secondary">
        <div class="card-header" >
            <h3>Editar afiliado</h3>
        </div>

        <div class="card-body">
            <form action={{ route('afiliados.update',['afiliado' => $afiliado->idAfiliado]) }} method="POST">
                @csrf
                @method('PATCH')
                
                <div class="form-group row">
                    <label for="nombre">Nombre completo del afiliado (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="nombre" name="nombre" placeholder="Nombre" required
                        value="{{ $afiliado->nombre }}"
                        >
                    </div>

                    <div class="col">
                        <input class="form-control" type="text" id="apellido" name="apellido" placeholder="Apellido" required
                        value="{{ $afiliado->apellido }}"
                        >    
                    </div>
                </div>

                <div class="form-group row">
                    <label for="dni">Dni (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="dni" name="dni" placeholder="Dni" required
                        value={{ $afiliado->dni }}
                        >
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email">Email</label>
                    <div class="col">
                        <input class="form-control" type="email" id="email" name="email" placeholder="ejemplo@ejemplo.com"
                        value="{{ $afiliado->email }}"
                        >
                    </div>
                </div>

                <div class="form-group row">
                    <label for="telefono">Telefono</label>
                    <div class="col">
                        <input class="form-control" type="text" id="telefono" name="telefono" placeholder="Prefijo sin el 0 y Nº sin el 15"
                        value={{ $afiliado->telefono }}
                        >
                    </div>

                </div>

                <div class="form-group row">
                    <label for="localidad">Localidad (*)</label>
                    <div class="col">
                        <input class="form-control" type="text" id="localidad" name="localidad" placeholder="Ciudad" required
                        value="{{$afiliado->localidad}}"
                        >
                    </div>
                </div>

                <div class="form-group row">
                    <label for="cantHijos">Cantidad de hijos (*)</label>
                    <div class="col">
                        <select class="form-select" name="cantHijos" id="cantHijos" required>
                            @if( $afiliado->cantidadHijos == 1 )
                                <option value="1" selected>1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            @endif

                            @if( $afiliado->cantidadHijos == 2 )
                                <option value="1">1</option>
                                <option value="2" selected>2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>    
                            @endif

                            @if( $afiliado->cantidadHijos == 3 )
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3" selected>3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            @endif

                            @if( $afiliado->cantidadHijos == 4 )
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4" selected>4</option>
                                <option value="5">5</option>
                            @endif

                            @if( $afiliado->cantidadHijos == 5 )
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5" selected>5</option>
                            @endif
                          </select>
                        
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tipo">Tipo de Empleado (*)</label>
                    <div class="col">
                        <select class="form-select" name="tipo" id="tipo" required>
                            @if( $afiliado->tipoEmpleado == 'publico' )
                                <option value="publico" selected>Empleado Público</option>
                                <option value="municipal">Empleado Municipal</option>
                            @else
                                <option value="publico">Empleado Público</option>
                                <option value="municipal" selected>Empleado Municipal</option>
                            @endif
                        </select>
                    </div>
                </div>

                <button class="btn btn-success" id="crear" type="submit">Editar</button>

            </form>
        </div>
    </div>
@endsection

upcn-utiles/resources/views/afiliados/index.blade.php
@extends('layouts.layout')

@section('title','Afiliados')

@section('content')
<div class="container">
    <div class="row text-center">
        <div class="col">
            <h2>Listado de Afiliados</h2>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <table class="table table-bordered table-striped" id="tablaAfiliados">
                        </div>
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>DNI</th>
                                <th>Email</th>
                                <th>Telefono</th>
                                <th>Localidad</th>
                                <th>Nº Hijos</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($afiliados as $afiliado)
                                <tr>
                                    <td>{{$afiliado->nombre}} </td>
                                    <td>{{$afiliado->apellido}}</td>
                                    <td>{{$afiliado->dni}}</td>
                                    <td>{{$afiliado->email}}</td>
                                    <td>{{$afiliado->telefono}}</td>
                                    <td>{{$afiliado->localidad}}</td>
                                    <td>{{$afiliado->cantidadHijos}}</td>
                                    
                                    <td>
                                        <a class="mx-2 btn btn-primary" title="Editar" href={{ route('afiliados.edit',['afiliado' => $afiliado->idAfiliado]) }}> 
                                            <i class="fa fa-user-edit fa-1x" aria-hidden="true"></i>
                                        </a>

                                        <a class="mx-2 btn btn-danger" title="Eliminar" data-toggle="modal" data-target="#delete_register{{$afiliado->idAfiliado}}" type="button">
                                            <i class="fa fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                                {{-- MODAL --}}
                                <div id="delete_register{{$afiliado->idAfiliado}}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="myModalLabel2">Eliminar Afiliado</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>

                                            <div class="modal-body">
                                                <h4>Seguro que desea eliminar a {{$afiliado->nombre}}?</h4>
                                            </div>
                                            
                                            <form action={{ route('afiliados.destroy',['afiliado' => $afiliado->idAfiliado]) }} method="POST">
                                                @csrf
                                                @method('DELETE')

                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    </div>
</div>

<script src={{ asset('js/afiliados/index.js') }}></script>

@endsection