upcn-utiles/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AfiliadoController;
use App\Http\Controllers\AsignacionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KitController;
//comentario
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function () {
    //Inicio
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');

    //Recursos ABMC
    Route::resources([
        'afiliados' => AfiliadoController::class,
        'asignaciones' => AsignacionController::class,
        'kits' => KitController::class
    ]);
    Route::get('/cargarStock',[KitController::class,'cargarStock'])->name('cargarStock');
    Route::post('/updateStock',[KitController::class,'updateStock'])->name('updateStock');
});

//Graficos
Route::get('/stock', [KitController::class, 'stock'])->name('stock');
Route::get('/stockGrafico', [KitController::class, 'stockGrafico'])->name('stockGrafico');
Route::get('/kitsEntregados', [KitController::class, 'kitsEntregados'])->name('kitsEntregados');
Route::get('/graficoKitsEntregados', [KitController::class, 'graficoKitsEntregados'])->name('graficoKitsEntregados');

//Datatables
Route::get('/datatable/asignaciones', [AsignacionController::class, 'asignaciones'])->name('datatable.asignaciones');

require __DIR__.'/auth.php';

upcn-utiles/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>UPCN - útiles</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

upcn-utiles/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <link rel="icon" type="image/png" href={{ asset('favicon.png') }}>
        <title>UPCN - útiles</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

upcn-utiles/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href={{ asset('favicon.png') }}>
    <link rel="stylesheet" href="{{ asset('css/layouts/layout.css') }}">
    
    <title>UPCN - @yield('title')</title>

    <!-- Usa Framework Boostrap en linea -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {{-- JQuery en linea --}}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {{-- Data table css--}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
    {{-- Para que el datatable sea responsive en cel --}}
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap4.min.css">
    {{-- SweetAlert --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script type="text/javascript" src="{{ asset('js/sidebar.js') }}"></script>
    {{-- AdminLTE 3 css--}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css">
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end" id="sidebar-wrapper" style=" background-color: rgb(16, 66, 104)">
            <div class="sidebar-heading border-bottom" style="padding: 0;">
                <a href={{ route('dashboard') }} class="brand-link">
                    <img src={{ asset('navbaricon.png') }} alt="Logo UPCN" class="brand-image">
                    <span class="brand-text font-weight-bold text-light">
                        UPCN
                    </span>
                    <span>
                        <i class="text-light" style="font-size: 50%">Seccional La Pampa</i>
                    </span>
                </a>
            </div>
            
            <div class="list-group list-group-flush" >
                <a style=" background-color: rgb(16, 66, 104)" class="text-light list-group-item list-group-item-action list-group-item p-3 " href={{ route('dashboard') }}>
                    <i class="fas fa-tachometer-alt"></i>Panel Informativo
                </a>

                <a style=" background-color: rgb(16, 66, 104)" href="#menuAfiliados" class="text-light list-group-item list-group-item-action list-group-item p-3 collapsed" data-toggle="collapse" aria-expanded="false"><i class="fas fa-user"></i> <span class="hidden-sm-down">Afiliados</span> <i class="fas fa-sort-down"></i></a>
                <div class="collapse" id="menuAfiliados" data-parent="#sidebar-wrapper">
                    <a style=" background-color: rgb(16, 66, 104)" href={{ route('afiliados.index') }} class="text-info list-group-item">Listado de Afiliados </a>
                    <a style=" background-color: rgb(16, 66, 104)" href={{ route('afiliados.create') }} class="text-info list-group-item">Crear Afiliado </a>
                </div>

                <a style=" background-color: rgb(16, 66, 104)" href="#menuAsignaciones" class="text-light list-group-item list-group-item-action list-group-item p-3 collapsed" data-toggle="collapse" aria-expanded="false"><i class="fas fa-file-signature"></i> <span class="hidden-sm-down">Asignaciones</span> <i class="fas fa-sort-down"></i></a>
                <div class="collapse" id="menuAsignaciones" data-parent="#sidebar-wrapper">
                    <a style=" background-color: rgb(16, 66, 104)" href={{route('asignaciones.create')}} class="text-info list-group-item">Entregar Kit </a>
                    <a style=" background-color: rgb(16, 66, 104)" href={{ route('asignaciones.index') }} class="text-info list-group-item">Listado de Asignaciones </a>
                </div>

                <a style=" background-color: rgb(16, 66, 104)" href="#menuKits" class="text-light list-group-item list-group-item-action list-group-item p-3 collapsed" data-toggle="collapse" aria-expanded="false"><i class="fas fa-pencil-ruler"></i> <span class="hidden-sm-down">Kits escolares</span> <i class="fas fa-sort-down"></i></a>
                <div class="collapse" id="menuKits" data-parent="#sidebar-wrapper">
                    <a style=" background-color: rgb(16, 66, 104)" href="{{route('kits.create')}}" class="text-info list-group-item">Agregar Kit </a>
                    <a style=" background-color: rgb(16, 66, 104)" href="{{route('cargarStock')}}" class="text-info list-group-item">Cargar Stock </a>
                    <a style=" background-color: rgb(16, 66, 104)" href="{{route('kits.index')}}" class="text-info list-group-item">Listado de Kits </a>
                </div>

                <a style=" background-color: rgb(16, 66, 104)" href={{route('logout')}} class="text-light list-group-item list-group-item-action list-group-item p-3">
                    <i class="fas fa-sign-out-alt"></i>Cerrar Sesión
                </a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="navbar-toggler" id="sidebarToggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid p-2">
                @if (session('success'))
                    <div class="alert alert-outline alert-success d-flex align-items-center" role="alert">
                        <i data-feather="alert-circle" class="mg-r-10">{{ session('success') }}</i>
                    </div>
                @endif

                @if (session('error'))
                    <div class="alert alert-outline alert-danger d-flex align-items-center" role="alert">
                        <i data-feather="alert-circle" class="mg-r-10">{{ session('error') }}</i>
                    </div>
                @endif
                
                @yield('content')
            </div>
        </div>
    </div>


    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {{-- DataTable JS --}}
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
    {{-- Para que sea responsive en celu --}}
    <script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap4.min.js"></script>
    {{-- AdminLTE 3 JS --}}
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
</body>
</html>

upcn-utiles/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>